[2025-06-18 17:15:08,057] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2025-06-18T17:15:07.624443+00:00 [queued]>
[2025-06-18 17:15:08,076] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2025-06-18T17:15:07.624443+00:00 [queued]>
[2025-06-18 17:15:08,077] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 17:15:08,077] {taskinstance.py:1096} INFO - Starting attempt 1 of 4
[2025-06-18 17:15:08,077] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 17:15:08,095] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-18T17:15:07.624443+00:00
[2025-06-18 17:15:08,100] {standard_task_runner.py:52} INFO - Started process 242 to run task
[2025-06-18 17:15:08,107] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2025-06-18T17:15:07.624443+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmp3me93sye', '--error-file', '/tmp/tmp2pgfeovk']
[2025-06-18 17:15:08,116] {standard_task_runner.py:77} INFO - Job 11: Subtask pyspark_train_classifier_model
[2025-06-18 17:15:08,180] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2025-06-18T17:15:07.624443+00:00 [running]> on host b08423263797
[2025-06-18 17:15:08,281] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-18T17:15:07.624443+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-18T17:15:07.624443+00:00
[2025-06-18 17:15:08,282] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-06-18 17:15:08,283] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\necho "Base Path: /opt/***/";\necho "Full File Path: /opt/***//resources/train_spark_mllib_model.py";\nspark-submit --master local[8]   /opt/***//resources/train_spark_mllib_model.py   /opt/***/']
[2025-06-18 17:15:08,294] {subprocess.py:74} INFO - Output:
[2025-06-18 17:15:08,298] {subprocess.py:78} INFO - Base Path: /opt/***/
[2025-06-18 17:15:08,299] {subprocess.py:78} INFO - Full File Path: /opt/***//resources/train_spark_mllib_model.py
[2025-06-18 17:15:10,371] {subprocess.py:78} INFO - WARNING: An illegal reflective access operation has occurred
[2025-06-18 17:15:10,372] {subprocess.py:78} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark-3.0.0-bin-hadoop3.2/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-06-18 17:15:10,372] {subprocess.py:78} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-06-18 17:15:10,372] {subprocess.py:78} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-06-18 17:15:10,372] {subprocess.py:78} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-06-18 17:15:10,906] {subprocess.py:78} INFO - 25/06/18 17:15:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-18 17:15:12,543] {subprocess.py:78} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-06-18 17:15:12,556] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO SparkContext: Running Spark version 3.0.0
[2025-06-18 17:15:12,604] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO ResourceUtils: ==============================================================
[2025-06-18 17:15:12,605] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO ResourceUtils: Resources for spark.driver:
[2025-06-18 17:15:12,605] {subprocess.py:78} INFO - 
[2025-06-18 17:15:12,606] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO ResourceUtils: ==============================================================
[2025-06-18 17:15:12,606] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO SparkContext: Submitted application: train_spark_mllib_model.py
[2025-06-18 17:15:12,705] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO SecurityManager: Changing view acls to: ***
[2025-06-18 17:15:12,705] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO SecurityManager: Changing modify acls to: ***
[2025-06-18 17:15:12,705] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO SecurityManager: Changing view acls groups to:
[2025-06-18 17:15:12,705] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO SecurityManager: Changing modify acls groups to:
[2025-06-18 17:15:12,705] {subprocess.py:78} INFO - 25/06/18 17:15:12 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-06-18 17:15:13,351] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO Utils: Successfully started service 'sparkDriver' on port 40657.
[2025-06-18 17:15:13,395] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO SparkEnv: Registering MapOutputTracker
[2025-06-18 17:15:13,442] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-18 17:15:13,475] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-18 17:15:13,475] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-18 17:15:13,482] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-18 17:15:13,500] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-7836f759-bbf4-4ab2-ba45-ad0cf32ca22d
[2025-06-18 17:15:13,521] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-18 17:15:13,544] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-18 17:15:13,827] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-18 17:15:13,908] {subprocess.py:78} INFO - 25/06/18 17:15:13 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://b08423263797:4040
[2025-06-18 17:15:14,397] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO Executor: Starting executor ID driver on host b08423263797
[2025-06-18 17:15:14,454] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45323.
[2025-06-18 17:15:14,456] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO NettyBlockTransferService: Server created on b08423263797:45323
[2025-06-18 17:15:14,463] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-18 17:15:14,479] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b08423263797, 45323, None)
[2025-06-18 17:15:14,488] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO BlockManagerMasterEndpoint: Registering block manager b08423263797:45323 with 434.4 MiB RAM, BlockManagerId(driver, b08423263797, 45323, None)
[2025-06-18 17:15:14,497] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b08423263797, 45323, None)
[2025-06-18 17:15:14,499] {subprocess.py:78} INFO - 25/06/18 17:15:14 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b08423263797, 45323, None)
[2025-06-18 17:15:15,450] {subprocess.py:78} INFO - 25/06/18 17:15:15 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/tmp/***tmpceeb39qh/spark-warehouse').
[2025-06-18 17:15:15,451] {subprocess.py:78} INFO - 25/06/18 17:15:15 INFO SharedState: Warehouse path is 'file:/tmp/***tmpceeb39qh/spark-warehouse'.
[2025-06-18 17:15:16,696] {subprocess.py:78} INFO - Traceback (most recent call last):
[2025-06-18 17:15:16,696] {subprocess.py:78} INFO -   File "/opt/***/resources/train_spark_mllib_model.py", line 190, in <module>
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -     main(sys.argv[1])
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -   File "/opt/***/resources/train_spark_mllib_model.py", line 59, in main
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -     features = spark.read.json(input_path, schema=schema)
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -   File "/opt/spark-3.0.0-bin-hadoop3.2/python/pyspark/sql/readwriter.py", line 300, in json
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -     return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -   File "/opt/spark-3.0.0-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -   File "/opt/spark-3.0.0-bin-hadoop3.2/python/pyspark/sql/utils.py", line 137, in deco
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -     raise_from(converted)
[2025-06-18 17:15:16,697] {subprocess.py:78} INFO -   File "<string>", line 3, in raise_from
[2025-06-18 17:15:16,705] {subprocess.py:78} INFO - pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/***/data/simple_flight_delay_features.jsonl.bz2;
[2025-06-18 17:15:16,744] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO SparkContext: Invoking stop() from shutdown hook
[2025-06-18 17:15:16,758] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO SparkUI: Stopped Spark web UI at http://b08423263797:4040
[2025-06-18 17:15:16,777] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-06-18 17:15:16,796] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO MemoryStore: MemoryStore cleared
[2025-06-18 17:15:16,797] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO BlockManager: BlockManager stopped
[2025-06-18 17:15:16,804] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-06-18 17:15:16,808] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-06-18 17:15:16,819] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO SparkContext: Successfully stopped SparkContext
[2025-06-18 17:15:16,819] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO ShutdownHookManager: Shutdown hook called
[2025-06-18 17:15:16,820] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-ef3347cb-91ac-4ffe-9856-2dbe313cb964/pyspark-00f0905f-d107-48e6-a88f-6e3a3d79504a
[2025-06-18 17:15:16,826] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-fcff2409-9bec-4586-aded-4617712abf65
[2025-06-18 17:15:16,832] {subprocess.py:78} INFO - 25/06/18 17:15:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-ef3347cb-91ac-4ffe-9856-2dbe313cb964
[2025-06-18 17:15:16,872] {subprocess.py:82} INFO - Command exited with return code 1
[2025-06-18 17:15:16,887] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2025-06-18 17:15:16,892] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250618T171507, start_date=20250618T171508, end_date=20250618T171516
[2025-06-18 17:15:16,926] {local_task_job.py:151} INFO - Task exited with return code 1
[2025-06-18 17:15:16,946] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
